global:
  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.data: DEBUG

  management:
    endpoints:
      shutdown:
        enabled: true
      web:
        exposure:
          include: "*"