server:
  port: 8761

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diveplanner
    username: diveplanner
    password: 06a2b74ff77bece27826551d8ca1fab1452dfe9c16f2afa862808d593c856cc0
    driver-class-name: org.postgresql.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    show-sql: true
    properties:
      hibernate:
    #        format_sql: true
    #        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/realms/dive-planner/protocol/openid-connect/certs
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: *
    health:
      show:
        details: always